apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: api-horizontalpodsutoscaler
    namespace: api-deployment
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: stock-service
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 10
