apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
    namespace: stockservice-jacksonveroneze
    labels:
        app: api-stock
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-stock
    template:
        metadata:
            labels:
                app: api-stock
        spec:
            containers:
                - name: api
                  image: 'jacksonveroneze.azurecr.io/stock-service:1.0.7'
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  env:
                      - name: APP_CONFIG_ConnectionStrings__DefaultConnection
                        valueFrom:
                            secretKeyRef:
                                name: api-secret
                                key: connectionString
                      - name: APP_CONFIG_Auth__Authority
                        valueFrom:
                            configMapKeyRef:
                                name: api-configmap
                                key: APP_CONFIG_Auth__Authority
                      - name: APP_CONFIG_Auth__Audience
                        valueFrom:
                            configMapKeyRef:
                                name: api-configmap
                                key: APP_CONFIG_Auth__Audience
                      - name: APP_CONFIG_Urls_Allow_Cors
                        valueFrom:
                            configMapKeyRef:
                                name: api-configmap
                                key: APP_CONFIG_Urls_Allow_Cors
                      - name: ASPNETCORE_ENVIRONMENT
                        valueFrom:
                            configMapKeyRef:
                                name: api-configmap
                                key: ASPNETCORE_ENVIRONMENT
