apiVersion: v1
kind: Service
metadata:
    name: api-service
    namespace: stock-application
spec:
    type: LoadBalancer
    selector:
        app: api-stock
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
