version: "3.8"

services:
    database_mssql:
        container_name: database_mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        restart: always
        environment:
            SA_PASSWORD: localPass@word
            ACCEPT_EULA: Y
        healthcheck:
            test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PlocalPass@word", "-Q", "select 1" ]
            interval: 60s
            timeout: 3s
            start_period: 5s
            retries: 3
        ports:
            - 1433:1433

volumes:
    database_mssql:
