version: "3.8"

services:
    traefik:
        container_name: traefik
        image: traefik:v2.4
        restart: always
        command:
            - --log.level=INFO
            - --api.insecure=true
            - --providers.docker=true
            - --providers.docker.exposedbydefault=false
            - --entrypoints.web.address=:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.docker.network=stock_network
        links:
            - api
        depends_on:
            - api
        ports:
            - 80:80
            - 8080:8080

    api:
        labels:
            - traefik.enable=true
            - traefik.http.routers.api.entrypoints=web
            - traefik.http.routers.api.rule=Host(`stockservice.jacksonveroneze.com`)
            - traefik.http.services.api.loadbalancer.server.port=80
            - traefik.http.middlewares.api-compress-md.compress=true
            - traefik.http.middlewares.api-ratelimit-md.ratelimit.average=10
            - traefik.http.middlewares.api-ratelimit-md.ratelimit.burst=10
            - traefik.http.middlewares.api-ratelimit-md.ratelimit.period=1
            - traefik.http.middlewares.api-request-body-md.buffering.maxRequestBodyBytes=2000000
            - traefik.http.middlewares.api-retry-md.retry.attempts=4
            - traefik.http.middlewares.api-retry-md.retry.initialinterval=100ms
            - traefik.http.routers.api.middlewares=api-compress-md,api-ratelimit-md,api-request-body-md,api-retry-md

networks:
    stock_network:
        external: true
