version: '3.7'

services:
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - default-network

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - 3000:3000
        networks:
            - default-network
        depends_on:
            - prometheus

networks:
    default-network:
