apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-deployment
    namespace: stock-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mssql-stock-service
    template:
        metadata:
            labels:
                app: mssql-stock-service
        spec:
            terminationGracePeriodSeconds: 30
            hostname: mssqlinst
            securityContext:
                fsGroup: 10001
            containers:
                - name: mssql
                  image: mcr.microsoft.com/mssql/server:2019-latest
                  ports:
                      - containerPort: 1433
                  env:
                      - name: MSSQL_PID
                        value: "Developer"
                      - name: ACCEPT_EULA
                        value: "Y"
                      - name: SA_PASSWORD
                        value: localPass@word
