apiVersion: v1
kind: Service
metadata:
    name: mssql-stock-service
    namespace: stock-service
spec:
    type: NodePort
    selector:
        app: mssql-stock-service
    ports:
        - protocol: TCP
          port: 1433
          targetPort: 1433
