apiVersion: v1
kind: Service
metadata:
    name: stock-service
    namespace: stock-service
spec:
    type: LoadBalancer
    selector:
        app: stock-service
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
