apiVersion: apps/v1
kind: Deployment
metadata:
    name: database-deployment
    namespace: stock-application
spec:
    replicas: 1
    selector:
        matchLabels:
            app: database-stock
    template:
        metadata:
            labels:
                app: database-stock
        spec:
            containers:
                - name: database
                  image: 'postgres:13-alpine'
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: database-secret
                                key: password
                  volumeMounts:
                      - mountPath: /var/lib/postgresql/data
                        name: database
            volumes:
                - name: database
                  persistentVolumeClaim:
                      claimName: database-persistentvolumeclaim
