apiVersion: v1
kind: PersistentVolume
metadata:
    name: database-persistentvolume-volume
    namespace: stockservice-jacksonveroneze
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /tmp
        type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: database-persistentvolumeclaim
    namespace: stockservice-jacksonveroneze
    labels:
        app: database-stock
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
