apiVersion: v1
kind: Service
metadata:
    name: database-service
    namespace: stock-application
spec:
    type: LoadBalancer
    selector:
        app: database-stock
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
