// <auto-generated />
using System;
using JacksonVeroneze.StockService.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JacksonVeroneze.StockService.Infra.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210306132816_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdjustmentItemMovementItem", b =>
                {
                    b.Property<Guid>("AdjustmentItemsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("adjustment_items_id");

                    b.Property<Guid>("MovementItemsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("movement_items_id");

                    b.HasKey("AdjustmentItemsId", "MovementItemsId")
                        .HasName("pk_adjustment_item_movement_item");

                    b.HasIndex("MovementItemsId")
                        .HasDatabaseName("ix_adjustment_item_movement_item_movement_items_id");

                    b.ToTable("adjustment_item_movement_item");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Adjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_adjustment");

                    b.ToTable("adjustment");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.AdjustmentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AdjustmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("adjustment_id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_adjustment_item");

                    b.HasIndex("AdjustmentId")
                        .HasDatabaseName("ix_adjustment_item_adjustment_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_adjustment_item_product_id");

                    b.ToTable("adjustment_item");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_movement");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_movement_product_id");

                    b.ToTable("movement");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.MovementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("movement_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_movement_item");

                    b.HasIndex("MovementId")
                        .HasDatabaseName("ix_movement_item_movement_id");

                    b.ToTable("movement_item");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Output", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_output");

                    b.ToTable("output");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.OutputItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("OutputId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("output_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_output_item");

                    b.HasIndex("OutputId")
                        .HasDatabaseName("ix_output_item_output_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_output_item_product_id");

                    b.ToTable("output_item");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("Description", "IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_product_description_is_active");

                    b.ToTable("product");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("description");

                    b.Property<int>("State")
                        .HasColumnType("int")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase");

                    b.ToTable("purchase");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.PurchaseItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("product_id");

                    b.Property<Guid>("PurchaseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("value");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_purchase_item");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchase_item_product_id");

                    b.HasIndex("PurchaseId")
                        .HasDatabaseName("ix_purchase_item_purchase_id");

                    b.ToTable("purchase_item");
                });

            modelBuilder.Entity("MovementItemOutputItem", b =>
                {
                    b.Property<Guid>("MovementItemsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("movement_items_id");

                    b.Property<Guid>("OutputItemsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("output_items_id");

                    b.HasKey("MovementItemsId", "OutputItemsId")
                        .HasName("pk_movement_item_output_item");

                    b.HasIndex("OutputItemsId")
                        .HasDatabaseName("ix_movement_item_output_item_output_items_id");

                    b.ToTable("movement_item_output_item");
                });

            modelBuilder.Entity("MovementItemPurchaseItem", b =>
                {
                    b.Property<Guid>("MovementItemsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("movement_items_id");

                    b.Property<Guid>("PurchaseItemsId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("purchase_items_id");

                    b.HasKey("MovementItemsId", "PurchaseItemsId")
                        .HasName("pk_movement_item_purchase_item");

                    b.HasIndex("PurchaseItemsId")
                        .HasDatabaseName("ix_movement_item_purchase_item_purchase_items_id");

                    b.ToTable("movement_item_purchase_item");
                });

            modelBuilder.Entity("AdjustmentItemMovementItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.AdjustmentItem", null)
                        .WithMany()
                        .HasForeignKey("AdjustmentItemsId")
                        .HasConstraintName("fk_adjustment_item_movement_item_adjustment_item_adjustment_items_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.MovementItem", null)
                        .WithMany()
                        .HasForeignKey("MovementItemsId")
                        .HasConstraintName("fk_adjustment_item_movement_item_movement_item_movement_items_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.AdjustmentItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Adjustment", "Adjustment")
                        .WithMany("Items")
                        .HasForeignKey("AdjustmentId")
                        .HasConstraintName("fk_adjustment_item_adjustment_adjustment_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Product", "Product")
                        .WithMany("ItemsAdjustment")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_adjustment_item_product_product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adjustment");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Movement", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Product", "Product")
                        .WithMany("ItemsMovement")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_movement_product_product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.MovementItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Movement", "Movement")
                        .WithMany("Items")
                        .HasForeignKey("MovementId")
                        .HasConstraintName("fk_movement_item_movement_movement_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.OutputItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Output", "Output")
                        .WithMany("Items")
                        .HasForeignKey("OutputId")
                        .HasConstraintName("fk_output_item_output_output_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Product", "Product")
                        .WithMany("ItemsOutput")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_output_item_product_product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Output");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.PurchaseItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Product", "Product")
                        .WithMany("ItemsPurchase")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_purchase_item_product_product_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.Purchase", "Purchase")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseId")
                        .HasConstraintName("fk_purchase_item_purchase_purchase_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("MovementItemOutputItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.MovementItem", null)
                        .WithMany()
                        .HasForeignKey("MovementItemsId")
                        .HasConstraintName("fk_movement_item_output_item_movement_item_movement_items_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.OutputItem", null)
                        .WithMany()
                        .HasForeignKey("OutputItemsId")
                        .HasConstraintName("fk_movement_item_output_item_output_item_output_items_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovementItemPurchaseItem", b =>
                {
                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.MovementItem", null)
                        .WithMany()
                        .HasForeignKey("MovementItemsId")
                        .HasConstraintName("fk_movement_item_purchase_item_movement_item_movement_items_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JacksonVeroneze.StockService.Domain.Entities.PurchaseItem", null)
                        .WithMany()
                        .HasForeignKey("PurchaseItemsId")
                        .HasConstraintName("fk_movement_item_purchase_item_purchase_item_purchase_items_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Adjustment", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Movement", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Output", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Product", b =>
                {
                    b.Navigation("ItemsAdjustment");

                    b.Navigation("ItemsMovement");

                    b.Navigation("ItemsOutput");

                    b.Navigation("ItemsPurchase");
                });

            modelBuilder.Entity("JacksonVeroneze.StockService.Domain.Entities.Purchase", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
