name: Docker

on:
    workflow_dispatch:

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    GenetateDocker:
        runs-on: Ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Build and push
              run: |
                echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
                docker build . --tag docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:0.0.1
                docker push docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:0.0.1
