name: Docker

on:
    release:
        types: [published]

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    TOKEN_REGISTRY_DIGITAL_OCEAN: ${{ secrets.TOKEN_REGISTRY_DIGITAL_OCEAN }}

jobs:
    genetate-publish:
        name: Generate and Publish
        runs-on: Ubuntu-20.04

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Build and push
              run: |
                docker build . --tag docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:${{ github.ref }}
                echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
                echo ${{ secrets.TOKEN_REGISTRY_DIGITAL_OCEAN }} | docker login https://registry.digitalocean.com -u $TOKEN_REGISTRY_DIGITAL_OCEAN --password-stdin

                docker push docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:${{ github.ref }}

                docker build . --tag docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:${{ github.ref }}
                docker push docker.pkg.github.com/jacksonveroneze/stock-service/stock-service:${{ github.ref }}
